### ISSUE TITLE
Remove an applications dependency's when uninstalling unless they are used by something else

### ISSUE THREAD

**Issue by Jacalz** [solus-project/solus-sc#166]
If you install a lot of applications and then remove the applications the dependency's that was downloaded for that application is left behind. This makes for a lot of unneeded/unused dependency's  that just bloat the system.

My solution for the problem would be to remove the dependency's that was installed with an application when you remove that application (if they are not used by another application or the system)

**Comment by ikeydoherty** [comment]
eopkg has no internal knowledge of who or what initiated the extra thing to be installed, so cannot determine an automatically installed vs a manually installed. This would also be in the scope of the package manager, not the software center.

I'm closing this for the above reasons, but because `sol` will be designed to handle orphans from day 1, and not suffer the design flaws of the seriously aged eopkg. :) sol will be our own replacement to eopkg (the thing we didn't create initially)
